linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gofmt

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: false

issues:
  exclude-dirs:
    - vendor
